<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lab01.Logic\Lab01.Logic.csproj" />
    <Resource Include="..\assets\wmremove-transformed.png" Link="wmremove-transformed.png" />
  </ItemGroup>

</Project>
